### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by flosse** [coop-care/org#4]
- [ ] Choose a site generator
- [x] Choose a theme
- [ ] Choose a name #1

**Comment by flosse** [comment]
Themes:
- ~https://www.getzola.org/themes/~
- https://html5up.net/
  - https://html5up.net/arcana
  - https://html5up.net/hyperspace
  - https://html5up.net/stellar
  - https://html5up.net/miniport
  - https://html5up.net/prologue
  - https://html5up.net/landed
  - https://html5up.net/dopetrope
  - https://html5up.net/spectral
- https://jamstackthemes.dev/ssg/jekyll/
  - https://themes.stackbit.com/demos/azimuth/
  - https://emilbaehr.github.io/automatic-app-landing-page/
  - https://forestryio.github.io/ubuild-jekyll/
  - ~https://wowthemesnet.github.io/affiliates-jekyll-theme/~
  - https://proud-alligator.cloudvent.net/
  - https://volny.github.io/creative-theme-jekyll/
- http://jekyllthemes.org/
- https://jekyllthemes.io/
- https://themes.gohugo.io/

Requirements:
- must have a menu
- must work on mobile
- should be licensed under an open license

**Comment by flosse** [comment]
Site generators

- https://www.getzola.org/
- https://gohugo.io/
- https://jekyllrb.com/

Requirements
- must work on Linux and Mac OS
- should support multi-lingual sites

**Comment by michaelkamphausen** [comment]
Wow, that's a lot of templates. 😲 

I also like [Story](https://html5up.net/story) because of the many possibilities to combine text and imagery and for including many elements, though it doesn't come with a menu.

[Ethereal](https://html5up.net/ethereal) stands out particularly to me, as it is quite unconventional, but I also find the warm sunrise color scheme quite inspiring. It includes elements, but no menu either. I suppose I really like elements. 😃 

Thinking about styles and color schemes, I begin to prefer something that doesn't look much like tech startup. I think about the potential audience and imagine people that are more human-centric and less tech-savvy, more relationship-oriented and less business-driven and more likely female than male. So I might prefer a warm color scheme over a classic blue or a dark one.
Oh dear, two hours ago I didn't care much about the design at all, how did I get to where I find myself now? 😄

Nevertheless, here are some additional themes I like, although some don't have menus (or elements) and don't necessarily fit my considerations from the previous paragraph:
* https://html5up.net/solid-state (quite dark, but I like the diagonal lines, plus it has elements _and_ a menu)
* https://html5up.net/spectral
* https://html5up.net/alpha
* https://html5up.net/miniport
* https://html5up.net/tessellate
* https://html5up.net/twenty
* https://themes.stackbit.com/demos/azimuth/
* https://forestryio.github.io/ubuild-jekyll/
* https://themes.gohugo.io/theme/hugo-elate-theme/
